service: jerry-web-worker
runtime: custom
env: flex

builtins:
- deferred: on

env_variables:
  CLOUD_SQL_CONNECTION_NAME: smart-radio-244817:us-east4-b:abs-ft
  DB_USER: postgres
  DB_PASS: my-db-pass
  DB_NAME: my_db

beta_settings:
  cloud_sql_instances: <INSTANCE_CONNECTION_NAME>=tcp:5432

handlers: - url: /_ah/queue/deferred
script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py login: admin

entrypoint: gunicorn -b :8080 main:app --timeout 180
