service: jerry-selenium-service
runtime: custom
env: flex

env_variables:
  CLOUD_SQL_CONNECTION_NAME: <MY-PROJECT>:<INSTANCE-REGION>:<MY-DATABASE>
  DB_USER: my-db-user
  DB_PASS: my-db-pass
  DB_NAME: my_db

beta_settings:
  cloud_sql_instances: <INSTANCE_CONNECTION_NAME>=tcp:5432

handlers: - url: /_ah/queue/deferred
script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py login: admin

entrypoint: gunicorn -b :$PORT main:app --timeout 180
